name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - uses: mlugg/setup-zig@v1
     - uses: pre-commit/action@v3.0.1
       with:
         extra_args: --all-files

  tests:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - uses: mlugg/setup-zig@v1
     - name: Build
       run: zig build test --summary all

  build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - uses: mlugg/setup-zig@v1
     - name: Build
       run: zig build

  check:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - lint
      - tests
      - build
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJson( needs ) }}
